use role securityadmin;

/*ALTER USER plakhanpal SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxA6YqPUKn9tLB9uaWdKX
hzRiYKy8MeWjqKR+33eAwtlWw57xc1uH1f7Gz+/hJ8UkMXM45WwzTN59KAPD5AnS
dzx1z4LRZiQXxYXceqTazVDhiwr72+YxLhA9TwG50+FDSaQU3BJjoOELIVXEwHNF
pYuFWY1Qf7lPjLVUhFjf++UeocRJhJJ81/goUB2V99xIsN5SlPOgsXT9mhV+3gFU
kfl/7JIJ0Qg9c1SOYmNbm/huGoGCjdcurAy0skfhizsUPoT6PYdKUGqTj7KGWFZ9
ctwVRfnSqSR58DNQ14rw/3pBYsYf1g2QFFWV7VRFQvYER7APpUNMxTxMHbNTksMM
rQIDAQAB';
*/

ALTER USER kipi_ltr_user SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxA6YqPUKn9tLB9uaWdKX
hzRiYKy8MeWjqKR+33eAwtlWw57xc1uH1f7Gz+/hJ8UkMXM45WwzTN59KAPD5AnS
dzx1z4LRZiQXxYXceqTazVDhiwr72+YxLhA9TwG50+FDSaQU3BJjoOELIVXEwHNF
pYuFWY1Qf7lPjLVUhFjf++UeocRJhJJ81/goUB2V99xIsN5SlPOgsXT9mhV+3gFU
kfl/7JIJ0Qg9c1SOYmNbm/huGoGCjdcurAy0skfhizsUPoT6PYdKUGqTj7KGWFZ9
ctwVRfnSqSR58DNQ14rw/3pBYsYf1g2QFFWV7VRFQvYER7APpUNMxTxMHbNTksMM
rQIDAQAB';

DESC USER kipi_ltr_user;
SELECT SUBSTR((SELECT "value" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
  WHERE "property" = 'RSA_PUBLIC_KEY_FP'), LEN('SHA256:') + 1);

-- U0bUwl8k5ubjHZmHTVMHVeOPpMXaoZi6/ZRV0InmKV8=

-- verify that above matches the result of the following:
--openssl rsa -pubin -in rsa_key.pub -outform DER | openssl dgst -sha256 -binary | openssl enc -base64